// Code generated by entc, DO NOT EDIT.

package multiplemany

import (
	"entgo.io/bug/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.MultipleMany {
	return predicate.MultipleMany(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.MultipleMany {
	return predicate.MultipleMany(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.MultipleMany {
	return predicate.MultipleMany(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.MultipleMany {
	return predicate.MultipleMany(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.MultipleMany {
	return predicate.MultipleMany(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.MultipleMany {
	return predicate.MultipleMany(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.MultipleMany {
	return predicate.MultipleMany(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.MultipleMany {
	return predicate.MultipleMany(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.MultipleMany {
	return predicate.MultipleMany(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// User1 applies equality check predicate on the "user_1" field. It's identical to User1EQ.
func User1(v int) predicate.MultipleMany {
	return predicate.MultipleMany(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUser1), v))
	})
}

// User2 applies equality check predicate on the "user_2" field. It's identical to User2EQ.
func User2(v int) predicate.MultipleMany {
	return predicate.MultipleMany(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUser2), v))
	})
}

// User1EQ applies the EQ predicate on the "user_1" field.
func User1EQ(v int) predicate.MultipleMany {
	return predicate.MultipleMany(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUser1), v))
	})
}

// User1NEQ applies the NEQ predicate on the "user_1" field.
func User1NEQ(v int) predicate.MultipleMany {
	return predicate.MultipleMany(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldUser1), v))
	})
}

// User1In applies the In predicate on the "user_1" field.
func User1In(vs ...int) predicate.MultipleMany {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.MultipleMany(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldUser1), v...))
	})
}

// User1NotIn applies the NotIn predicate on the "user_1" field.
func User1NotIn(vs ...int) predicate.MultipleMany {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.MultipleMany(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldUser1), v...))
	})
}

// User2EQ applies the EQ predicate on the "user_2" field.
func User2EQ(v int) predicate.MultipleMany {
	return predicate.MultipleMany(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUser2), v))
	})
}

// User2NEQ applies the NEQ predicate on the "user_2" field.
func User2NEQ(v int) predicate.MultipleMany {
	return predicate.MultipleMany(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldUser2), v))
	})
}

// User2In applies the In predicate on the "user_2" field.
func User2In(vs ...int) predicate.MultipleMany {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.MultipleMany(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldUser2), v...))
	})
}

// User2NotIn applies the NotIn predicate on the "user_2" field.
func User2NotIn(vs ...int) predicate.MultipleMany {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.MultipleMany(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldUser2), v...))
	})
}

// HasUser1 applies the HasEdge predicate on the "user1" edge.
func HasUser1() predicate.MultipleMany {
	return predicate.MultipleMany(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(User1Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, User1Table, User1Column),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUser1With applies the HasEdge predicate on the "user1" edge with a given conditions (other predicates).
func HasUser1With(preds ...predicate.User) predicate.MultipleMany {
	return predicate.MultipleMany(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(User1InverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, User1Table, User1Column),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser2 applies the HasEdge predicate on the "user2" edge.
func HasUser2() predicate.MultipleMany {
	return predicate.MultipleMany(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(User2Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, User2Table, User2Column),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUser2With applies the HasEdge predicate on the "user2" edge with a given conditions (other predicates).
func HasUser2With(preds ...predicate.User) predicate.MultipleMany {
	return predicate.MultipleMany(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(User2InverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, User2Table, User2Column),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MultipleMany) predicate.MultipleMany {
	return predicate.MultipleMany(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MultipleMany) predicate.MultipleMany {
	return predicate.MultipleMany(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MultipleMany) predicate.MultipleMany {
	return predicate.MultipleMany(func(s *sql.Selector) {
		p(s.Not())
	})
}
