// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MultipleManiesColumns holds the columns for the "multiple_manies" table.
	MultipleManiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_1", Type: field.TypeInt},
		{Name: "user_2", Type: field.TypeInt},
	}
	// MultipleManiesTable holds the schema information for the "multiple_manies" table.
	MultipleManiesTable = &schema.Table{
		Name:       "multiple_manies",
		Columns:    MultipleManiesColumns,
		PrimaryKey: []*schema.Column{MultipleManiesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "multiple_manies_users_multiple_many_1",
				Columns:    []*schema.Column{MultipleManiesColumns[1]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "multiple_manies_users_multiple_many_2",
				Columns:    []*schema.Column{MultipleManiesColumns[2]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MultipleManiesTable,
		UsersTable,
	}
)

func init() {
	MultipleManiesTable.ForeignKeys[0].RefTable = UsersTable
	MultipleManiesTable.ForeignKeys[1].RefTable = UsersTable
}
