// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"entgo.io/bug/ent/migrate"

	"entgo.io/bug/ent/multiplemany"
	"entgo.io/bug/ent/user"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// MultipleMany is the client for interacting with the MultipleMany builders.
	MultipleMany *MultipleManyClient
	// User is the client for interacting with the User builders.
	User *UserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.MultipleMany = NewMultipleManyClient(c.config)
	c.User = NewUserClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:          ctx,
		config:       cfg,
		MultipleMany: NewMultipleManyClient(cfg),
		User:         NewUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:          ctx,
		config:       cfg,
		MultipleMany: NewMultipleManyClient(cfg),
		User:         NewUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		MultipleMany.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.MultipleMany.Use(hooks...)
	c.User.Use(hooks...)
}

// MultipleManyClient is a client for the MultipleMany schema.
type MultipleManyClient struct {
	config
}

// NewMultipleManyClient returns a client for the MultipleMany from the given config.
func NewMultipleManyClient(c config) *MultipleManyClient {
	return &MultipleManyClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `multiplemany.Hooks(f(g(h())))`.
func (c *MultipleManyClient) Use(hooks ...Hook) {
	c.hooks.MultipleMany = append(c.hooks.MultipleMany, hooks...)
}

// Create returns a create builder for MultipleMany.
func (c *MultipleManyClient) Create() *MultipleManyCreate {
	mutation := newMultipleManyMutation(c.config, OpCreate)
	return &MultipleManyCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of MultipleMany entities.
func (c *MultipleManyClient) CreateBulk(builders ...*MultipleManyCreate) *MultipleManyCreateBulk {
	return &MultipleManyCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for MultipleMany.
func (c *MultipleManyClient) Update() *MultipleManyUpdate {
	mutation := newMultipleManyMutation(c.config, OpUpdate)
	return &MultipleManyUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MultipleManyClient) UpdateOne(mm *MultipleMany) *MultipleManyUpdateOne {
	mutation := newMultipleManyMutation(c.config, OpUpdateOne, withMultipleMany(mm))
	return &MultipleManyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MultipleManyClient) UpdateOneID(id int) *MultipleManyUpdateOne {
	mutation := newMultipleManyMutation(c.config, OpUpdateOne, withMultipleManyID(id))
	return &MultipleManyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for MultipleMany.
func (c *MultipleManyClient) Delete() *MultipleManyDelete {
	mutation := newMultipleManyMutation(c.config, OpDelete)
	return &MultipleManyDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *MultipleManyClient) DeleteOne(mm *MultipleMany) *MultipleManyDeleteOne {
	return c.DeleteOneID(mm.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *MultipleManyClient) DeleteOneID(id int) *MultipleManyDeleteOne {
	builder := c.Delete().Where(multiplemany.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MultipleManyDeleteOne{builder}
}

// Query returns a query builder for MultipleMany.
func (c *MultipleManyClient) Query() *MultipleManyQuery {
	return &MultipleManyQuery{
		config: c.config,
	}
}

// Get returns a MultipleMany entity by its id.
func (c *MultipleManyClient) Get(ctx context.Context, id int) (*MultipleMany, error) {
	return c.Query().Where(multiplemany.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MultipleManyClient) GetX(ctx context.Context, id int) *MultipleMany {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser1 queries the user1 edge of a MultipleMany.
func (c *MultipleManyClient) QueryUser1(mm *MultipleMany) *UserQuery {
	query := &UserQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := mm.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(multiplemany.Table, multiplemany.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, multiplemany.User1Table, multiplemany.User1Column),
		)
		fromV = sqlgraph.Neighbors(mm.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryUser2 queries the user2 edge of a MultipleMany.
func (c *MultipleManyClient) QueryUser2(mm *MultipleMany) *UserQuery {
	query := &UserQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := mm.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(multiplemany.Table, multiplemany.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, multiplemany.User2Table, multiplemany.User2Column),
		)
		fromV = sqlgraph.Neighbors(mm.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *MultipleManyClient) Hooks() []Hook {
	return c.hooks.MultipleMany
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Create returns a create builder for User.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(u *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(u))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id int) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *UserClient) DeleteOne(u *User) *UserDeleteOne {
	return c.DeleteOneID(u.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *UserClient) DeleteOneID(id int) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id int) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id int) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryMultipleMany1 queries the multiple_many_1 edge of a User.
func (c *UserClient) QueryMultipleMany1(u *User) *MultipleManyQuery {
	query := &MultipleManyQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(multiplemany.Table, multiplemany.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.MultipleMany1Table, user.MultipleMany1Column),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryMultipleMany2 queries the multiple_many_2 edge of a User.
func (c *UserClient) QueryMultipleMany2(u *User) *MultipleManyQuery {
	query := &MultipleManyQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(multiplemany.Table, multiplemany.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.MultipleMany2Table, user.MultipleMany2Column),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}
