// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/bug/ent/multiplemany"
	"entgo.io/bug/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MultipleManyDelete is the builder for deleting a MultipleMany entity.
type MultipleManyDelete struct {
	config
	hooks    []Hook
	mutation *MultipleManyMutation
}

// Where appends a list predicates to the MultipleManyDelete builder.
func (mmd *MultipleManyDelete) Where(ps ...predicate.MultipleMany) *MultipleManyDelete {
	mmd.mutation.Where(ps...)
	return mmd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mmd *MultipleManyDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(mmd.hooks) == 0 {
		affected, err = mmd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MultipleManyMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			mmd.mutation = mutation
			affected, err = mmd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(mmd.hooks) - 1; i >= 0; i-- {
			if mmd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = mmd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mmd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (mmd *MultipleManyDelete) ExecX(ctx context.Context) int {
	n, err := mmd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mmd *MultipleManyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: multiplemany.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: multiplemany.FieldID,
			},
		},
	}
	if ps := mmd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, mmd.driver, _spec)
}

// MultipleManyDeleteOne is the builder for deleting a single MultipleMany entity.
type MultipleManyDeleteOne struct {
	mmd *MultipleManyDelete
}

// Exec executes the deletion query.
func (mmdo *MultipleManyDeleteOne) Exec(ctx context.Context) error {
	n, err := mmdo.mmd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{multiplemany.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mmdo *MultipleManyDeleteOne) ExecX(ctx context.Context) {
	mmdo.mmd.ExecX(ctx)
}
