// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/bug/ent/user"
	"entgo.io/ent/dialect/sql"
)

// User is the model entity for the User schema.
type User struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges UserEdges `json:"edges"`
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// MultipleMany1 holds the value of the multiple_many_1 edge.
	MultipleMany1 []*MultipleMany `json:"multiple_many_1,omitempty"`
	// MultipleMany2 holds the value of the multiple_many_2 edge.
	MultipleMany2 []*MultipleMany `json:"multiple_many_2,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// MultipleMany1OrErr returns the MultipleMany1 value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) MultipleMany1OrErr() ([]*MultipleMany, error) {
	if e.loadedTypes[0] {
		return e.MultipleMany1, nil
	}
	return nil, &NotLoadedError{edge: "multiple_many_1"}
}

// MultipleMany2OrErr returns the MultipleMany2 value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) MultipleMany2OrErr() ([]*MultipleMany, error) {
	if e.loadedTypes[1] {
		return e.MultipleMany2, nil
	}
	return nil, &NotLoadedError{edge: "multiple_many_2"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type User", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (u *User) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			u.ID = int(value.Int64)
		}
	}
	return nil
}

// QueryMultipleMany1 queries the "multiple_many_1" edge of the User entity.
func (u *User) QueryMultipleMany1() *MultipleManyQuery {
	return (&UserClient{config: u.config}).QueryMultipleMany1(u)
}

// QueryMultipleMany2 queries the "multiple_many_2" edge of the User entity.
func (u *User) QueryMultipleMany2() *MultipleManyQuery {
	return (&UserClient{config: u.config}).QueryMultipleMany2(u)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (u *User) Update() *UserUpdateOne {
	return (&UserClient{config: u.config}).UpdateOne(u)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (u *User) Unwrap() *User {
	tx, ok := u.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	u.config.driver = tx.drv
	return u
}

// String implements the fmt.Stringer.
func (u *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v", u.ID))
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User

func (u Users) config(cfg config) {
	for _i := range u {
		u[_i].config = cfg
	}
}
